export type ScreenContent = Record<string, any>;

export const DEFAULT_SCREENS: Record<string, ScreenContent> = {
  common: {
    loading: 'Se încarcă…',
    cancel: 'Anulează',
    save: 'Salvează',
    delete: 'Șterge',
    edit: 'Editează',
    error_generic: 'A apărut o eroare. Încearcă din nou.',
  },
  dashboard: {
    stat_unpaid_balance: 'Sold total neachitat',
    stat_open_invoices: 'Facturi deschise',
    stat_paid_invoices: 'Facturi achitate',
    stat_arrears: 'Restanțe',
    stat_homes: 'Locuințe',
    vezi: 'vezi',
    support: 'Susține proiectul nostru',
    empty: 'Nu ai nicio locuință încă.',
    fab_home: 'Locuință',
    fab_utility: 'Utilitate',
    error_load: 'Nu s-au putut încărca datele.',
  },
  homes: {
    accounts_chip: '{count} conturi',
    unpaid_chip: '{count} neplătite',
    empty: 'Nu ai nicio locuință încă.',
    fab_home: 'Locuință',
    fab_utility: 'Utilitate',
    error_load: 'Nu s-au putut încărca locuințele.',
  },
  invoices: {
    group_others: 'Altele',
    default_title: 'Factură',
    period: 'Perioada {value}',
    due: 'Scadență {value}',
    paid: 'Plătită',
    unpaid: 'Neplătită',
    empty: 'Nicio factură disponibilă.',
    error_load: 'Nu s-au putut încărca facturile.',
    delete_title: 'Șterge factura',
    delete_confirm: 'Sigur vrei să ștergi această factură?',
    error_save: 'Operațiunea a eșuat.',
    error_delete: 'Ștergerea a eșuat.',
  },
  notifications: {
    title: 'Notificări',
    read_all: 'Marchează toate ca citite',
    empty: 'Nicio notificare încă.',
    default_title: 'Notificare',
    error_load: 'Nu s-au putut încărca notificările.',
    badge: {
      invoice: { label: 'Factură', color: '#16a34a' },
      unpaid: { label: 'Neachitat', color: '#f59e0b' },
      admin: { label: 'Administrație', color: '#dc2626' },
      general: { label: 'General', color: '#0d9488' },
      other: { label: 'Altele', color: '#0d9488' },
    },
    new_invoice_title: 'Factură nouă 🔔',
    new_invoice_intro: 'S-a găsit factură nouă:',
    new_invoice_line: '• {home} · {utility} — {amount} MDL',
    new_invoice_more: '+{count} facturi în plus',
    new_invoice_total: 'Total: {total} MDL',
  },
  home_detail: {
    contract: 'Contract: {value}',
    floor: 'Etaj {value}',
    status_active: 'Activ',
    status_disabled: 'Dezactivat',
    empty: 'Niciun cont de utilități adăugat.',
    error_load: 'Nu s-au putut încărca datele.',
  },
  account_detail: {
    contract: 'Contract: {value}',
    location: 'Loc: {value}',
    refresh: 'Actualizează facturi',
    edit: 'Editează',
    invoices_title: 'Facturi',
    status_paid: 'Plătită',
    status_unpaid: 'Neplătită',
    status_unknown: 'Necunoscută',
    empty: 'Nicio factură. Apasă „Actualizează facturi”.',
    connect_error_title: 'Nu s-a putut conecta',
    connect_error_body: 'Conectare eșuată la furnizor.',
    refresh_done: 'Facturile au fost actualizate. Sold neplătit: {unpaid} MDL.',
    error_load: 'Nu s-au putut încărca datele contului.',
    error_save: 'Actualizarea a eșuat.',
  },
  home_form: {
    title_new: 'Locuință nouă',
    title_edit: 'Editează locuința',
    label_name: 'Nume *',
    placeholder_name: 'ex. Apartament 12',
    label_address: 'Adresă',
    label_floor: 'Etaj',
    label_sector: 'Sector',
    warn_required_name: 'Numele este obligatoriu.',
    error_load: 'Locuința nu a putut fi încărcată.',
    error_save: 'Salvarea a eșuat.',
  },
  account_form: {
    title_new: 'Utilitate nouă',
    title_edit: 'Editează contul',
    section_home: 'Locuință *',
    section_provider: 'Furnizor *',
    picker_provider: 'Selectează furnizorul',
    provider_label: '{icon} {name}',
    provider_readonly: 'Furnizorul nu poate fi schimbat după creare.',
    label_contract: 'Număr contract / identificator *',
    empty_homes: 'Nu ai nicio locuință. Creează întâi o locuință.',
    warn_provider: 'Selectează un furnizor.',
    warn_contract: 'Completează numărul de contract / identificatorul.',
    warn_home: 'Selectează locuința.',
    modal_title: 'Furnizor',
    error_load: 'Datele de formular nu au putut fi încărcate.',
    error_save: 'Salvarea a eșuat.',
  },
  profile: {
    name_label: 'Nume, Prenume',
    save_name: 'Salvează numele',
    name_saved: 'Numele a fost salvat.',
    settings: 'Setări',
    change_password: 'Schimbă parola',
    password_changed: 'Parola a fost schimbată.',
    language: 'Limba platformei',
    language_title: 'Limba',
    notifications: 'Notificări',
    notif_on: 'Activat — primești notificări pentru facturi noi',
    notif_off: 'Dezactivat — fără notificări push',
    notif_activated: 'Ai activat notificările. Notificarea de test a fost trimisă.',
    password_title: 'Schimbă parola',
    password_current: 'Parola curentă',
    password_new: 'Parola nouă (min 6 caractere)',
    password_confirm: 'Confirmă parola',
    password_warn_complete: 'Completează parola curentă și cea nouă.',
    password_warn_length: 'Parola nouă trebuie să aibă minim 6 caractere.',
    password_warn_mismatch: 'Parolele nu coincid.',
    deactivate: 'Dezactivarea contului',
    deactivate_title: 'Dezactivare cont',
    deactivate_confirm: 'Sigur vrei să dezactivezi contul? Vei fi deconectat.',
    deactivate_btn: 'Dezactivează',
    logout_btn: 'Deconectează-te',
    section_channel: 'Canal de actualizare',
    beta_desc:
      'Build din ramura deploy — actualizare directă, detectată după SHA-ul noului build',
    version: 'Versiune instalată: v{value}',
    check_updates: 'Verifică actualizări',
    section_account: 'Cont',
    logout: 'Deconectare',
    up_to_date: 'La zi',
    update_manual_open:
      'Nu am putut descărca/instala APK-ul. Deschide fișierul apk-ului din GitHub release.',
  },
};